version: "3"
services:
    passwordapi:
        image: nicopaez/password-api
        scale: 2
    nginx:
        image: nginx
        ports:
            - "8080:80"
        volumes:
            - './nginx.conf:/etc/nginx/nginx.conf'
        depends_on:
            - passwordapi

